### ISSUE TITLE
Say more about team formation and the discontinuation of type inventories?

### ISSUE THREAD

**Issue by ProfJanetDavis** [grinnell-cs/csc32x-sigcse2019#4]
Address further or let it go?

Reviewer 1: "I had concerns about the use of the Myers-Briggs or Strengths Finder but as noted in the footnote, these have been discontinued. It'd be pertinent to include a discussion point about why this is the case in the oral presentation as it is likely that not everyone is aware of the demerits. Also, there is still evidence of the value of diverse groups but more so for diversity of ideas within the group and this need not emerge diagnostically but can be externally enforced."

Reviewer 5: "Also, the authors reference a set of instruments that the career development office offered for helping students think about interpersonal skills and collaboration. Yet, they also include a footnote that the instruments have been discredited by their psychology department. The footnote indicates that there is some benefit from the ideas behind the instruments, but this feels incomplete and somehow important to a larger discussion about professionalizing our students through practical experience."

**Comment by rebelsky** [comment]
I extended the footnote to explain what we currently do and what some of the benefits are.  Let me know what you think.

Should we add a section about this approach in the "Recommendations"?  Probably not, because we don't have room.  But I thought I should raise the issue.

**Comment by rebelsky** [comment]
I don't think we need to address the issue of diverse teams.  (And I think you've said that already.)

**Comment by ProfJanetDavis** [comment]
I changed several uses of "group" to "team." Otherwise looks good. Thanks!
