### ISSUE TITLE
Move section 6 earlier in the paper? 

### ISSUE THREAD

**Issue by ProfJanetDavis** [grinnell-cs/csc32x-sigcse2019#5]
Reviewer 1: "The place of section 6 was a little unclear because it came after the conclusion. While I understand the need to place auxiliary information at the end. I think in an experience report, the information covers the important requirement of an experience report  - "All papers in this track should provide enough detail so that others could adopt the new innovation." and can therefore go with or after section 3."

**Comment by rebelsky** [comment]
I don't like the idea of putting it much earlier.  Recommendations should come after most of the paper is done, when people understand the context.  We could take most of section 6 and call it "Recommendations".  The first paragraph of the current section 6 would then be "Conclusion".  But I'm not sure it makes a big difference.  I didn't see the concern from other reviewers or the meta-review.   My temptation is to leave things as they are.

**Comment by ProfJanetDavis** [comment]
That's fine.
