### ISSUE TITLE
Reference more related work

### ISSUE THREAD

**Issue by ProfJanetDavis** [grinnell-cs/csc32x-sigcse2019#6]
Reviewer 1: "Apart from the mention of EPICS, references to a lot of prior work is missing especially those from prior SIGCSE. [Gonzales, Abigail Hawkins, and Laurie Miller Nelson. "Learner-Centered Instruction Promotes Student Success: Northface University Prepares Its Computer Science Students for the Workplace with Real-World Projects." THE Journal (Technological Horizons In Education) 32.6 (2005): 10.], [Liu, Chang. "Enriching software engineering courses with service-learning projects and the open-source approach." Proceedings of the 27th international conference on Software engineering. ACM, 2005.], [Buckley, Michael, et al. "Benefits of using socially-relevant projects in computer science and engineering education." ACM SIGCSE Bulletin. Vol. 36. No. 1. ACM, 2004.] "

Janet would also like to cite one of Z Sweedyk's papers on educational games in a software development course.

**Comment by rebelsky** [comment]
It's my feeling that Real-World projects are now a fairly standard part of the Software Design curriculum at most institutions.  A few citations wouldn't hurt.  But the important issue, which we should highlight, is that the experience of doing socially relevant projects is particularly meaningful.  It looks like the Liu and Buckley papers are likely to be useful.

I'm happy if you add one of Z's papers and provide some context.  Then we'll have the joy of finding more to cut :-).

**Comment by rebelsky** [comment]
I'm trying to decide how much context to add.  We don't have a related work section, but we also don't really have room for one.  Adding too much comparison feels defensive.  I've added a bit of comparison to the sections on local non-profits (distinguishing us from FOSS) and the section on multi-semester projects (distinguishing us from some other community-focused projects).

**Comment by rebelsky** [comment]
The overall comment from the APC was "Some reviewers suggested additional relevant literature that could be discussed to put the project into better context and highlight its novel contributions."  I'd say that the multi-semester and community-partner aspects were clearly grounded in the EPICS work and are therefore not particularly novel.  It's worth citing the literature and I think we need to emphasize Susan's suggestion that for many of the partners, the process is more important than the product.  (That wasn't our original intent, but I do think it's a novel approach.)  The more novel contribution is how everything ties together (plus the alumni mentors and the clear partnership with CLS).

**Comment by ProfJanetDavis** [comment]
I'm satisfied with what you did. I added a couple references to Z's work (which I now want to look more closely at for Whitman's software design course).
