### ISSUE TITLE
Mention final reflective essays in section on Outcomes?

### ISSUE THREAD

**Issue by ProfJanetDavis** [grinnell-cs/csc32x-sigcse2019#7]
Inspired by EPICS, I assigned a small portfolio of reflective essays in lieu of a final exam, which may provide some evidence for these outcomes. Sam, did you continue to assign those essays? If so, are they worth mentioning?

**Comment by rebelsky** [comment]
I did continue assigning a small portfolio of reflective essays, although I'm not sure that they are the same.  One page on some technical skill they'vedeveloped.  One page on some nontechnical skill they've developed.  One or two pages presenting a piece of code they found of value and an explanation thereof.  

However, given that we are struggling with length, I'm not sure that it's worth including.

**Comment by ProfJanetDavis** [comment]
Works for me.
