### ISSUE TITLE
Subsections and Subsubsections

### ISSUE THREAD

**Issue by rebelsky** [grinnell-cs/csc32x-sigcse2019#8]
I realized that Section 3 had only one subsection (3.1), which seemed somewhat pointless.  Since I worried about the length cost of converting every subsubsection to a subsection, I ended up writing a short macro that substitutes for the subsubsection.  

1. Does that seem okay?
2. We'd gain a lot of space doing something similar in sections 4 and 6.  Is that too much of a violation of standards?

**Comment by ProfJanetDavis** [comment]
Yeah, it is a violation of standards. Let me think about it. 

I could not figure out what you had done until I saw in the makefile you had changed the name of the main document. That would have been nice to mention.

**Comment by ProfJanetDavis** [comment]
The paper is now the right length, and I've made my piece with it.
